apiVersion: v2
name: cloudforge
description: CloudForge - Cloud-native microservice operations platform
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: postgresql
    version: "~15.5"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: postgresql.enabled
  - name: redis
    version: "~19.5"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: redis.enabled
