apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudforge.fullname" . }}-secret
  labels:
    {{- include "cloudforge.labels" . | nindent 4 }}
type: Opaque
stringData:
  CF_DATABASE_URL: {{ .Values.secrets.databaseUrl | default (printf "postgresql+asyncpg://%s:%s@%s:%d/%s" .Values.postgresql.username .Values.postgresql.password .Values.postgresql.host (int .Values.postgresql.port) .Values.postgresql.database) | quote }}
  CF_REDIS_URL: {{ .Values.secrets.redisUrl | default (printf "redis://%s:%d/0" .Values.redis.host (int .Values.redis.port)) | quote }}
  CF_SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
