apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudforge.fullname" . }}-secret
  labels:
    {{- include "cloudforge.labels" . | nindent 4 }}
type: Opaque
stringData:
  CF_DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  CF_REDIS_URL: {{ .Values.secrets.redisUrl | quote }}
  CF_SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
